### ISSUE TITLE
Quality control vignette review

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#10]
Here is feedback on the quality control vignette:

- [x] 1. I was surprised by the work flow to run tab_completeness without running read_results and read_dqo.  The vignette makes it sound like this would be the preferred work flow, but I think the standard work flow would be the opposite - to run read_results then read_dqos then tab_completeness.  That would be a clear work flow for people to understand.
- [x] 2. Just to confirm, I assume you are still planning to create a single function that will run the full QC Review report, which would internally use the tab_completeness function.  So users would not have to run the tab_completeness function by itself.
- [x] 3. In the completeness summary table, I think we do need a Hit/Miss column because users won't always be printing in color.
- [x] 4. In the completeness summary table, remember to leave a user-fillable column for Number of Censored Records.
- [x] 5. In the description of the frequency summary table, you mention "the percentage of observations in the results file that satisfy the checks".  Instead, I would describe this as "the number of quality control checks that were performed as a percentage of total observations".
- [x] 6. I assume you are still building the frequency summary table that shows a separate row for each QC type and parameter, with Number of Dups/Blanks/Spikes.

**Comment by fawda123** [comment]
@ben-wetherill can you please review the text in the updated [QC vignette](https://massbays-tech.github.io/MassWateR/reference/tabMWRfre.html)?  It has updated text for the frequency and completeness checks.  

And yes, when I'm done writing all the core functions, I will roll them all into a single QC function to generate all output together.  It will follow a workflow similar to your first bullet point above.

**Comment by ben-wetherill** [comment]
It's looking good.  Here are some suggestions:

1. The section labeled "Quality Control for Frequency and Completeness" can be removed, and you could move most of the text to the Frequency section.  It is not valid for the Completeness section because completeness is not about the number of QC samples.  It is only about the number of qualified samples.
2. In the Frequency summary table, I think we want to divide the Lab Spikes section into two sections - one for lab samples and one for in-situ instrument readings ("Instrument Checks").  Lab Spikes doesn't make sense for instruments.  The differentiation would be based on characteristic name.  I think this is safe, with the exception of dissolved oxygen maybe.  I will send an updated version of the parameter mapping file with this distinction.
3. I made two small changes directly in the vignette.  Did you see them?

**Comment by fawda123** [comment]
@ben-wetherill I think I've got the lab spike and instrument checks separated correctly in `qcMWRfre` and `tabMWRfre`.  They're separated based on the activity type and I applied the Spike/Check Accuracy values to both in creating the summary table.  The frequency table is the same, just not separating the two.

**Comment by ben-wetherill** [comment]
Ideally, we would only want to list the characteristics that are relevant for lab spikes or calibration checks.  Each characteristic should only be under one or the other (Lab Spike or Instrument Check).  So, I think we do need to use the Method column in the Parameter Mapping file to distinguish.

I noticed that qcMWRfre() lists three rows now:  Lab Spike, Instrument Check, and Spike/Check Accuracy.  I'm thinking that you don't need to do this, because Spike/Check Accuracy would just be the sum of the first two.

**Comment by fawda123** [comment]
@ben-wetherill @carrjill I think I've got the all of the core functions done for the QC checks - accuracy, frequency, and completeness.  The latest addition is the accuracy checks.  So, when able, please review the vignette for the QC workflow: https://massbays-tech.github.io/MassWateR/ Please add your comments to this issue thread. 

Once we're satisified with the functionality and we're sure it's doing what we intend, I can build out the functions for compiling the results in a report.

**Comment by ben-wetherill** [comment]
The vignette looks good.

1. Do you want to simplify the code for accchk to use "Instrument Checks" instead of "Instrument Checks (post sampling)"?
2. The % Acceptance (pass_thr) for tabMWRacc() should be equal to the % Completeness threshold in the DQOCompleteness file.  It's not exactly the same thing, but the value should be the same.  For example, if the completeness target for Nitrate is 80% of records not qualified, then the acceptance rate for Nitrate QC checks should be 80% of QC checks pass.  pass_thr should not default to 90%.
3. For the cases where accuracy is calculated based on log values (e.g. E.coli), I'm thinking we need to make this clear in the tabMWRacc(individual) output, to avoid confusion.  Can we write "logRPD" instead of "RPD" when the calculation is based on log?
4. Don't forget about using the Method column to distinguish between Lab Spikes and Instrument Checks in tabMWRfre() to filter the list of parameters in each.

**Comment by ben-wetherill** [comment]
This issue thread is starting to get very long and hard to keep track of what has been resolved and what hasn't.

**Comment by ben-wetherill** [comment]
All look good, except #4 using the Method column to distinguish between Lab Spikes and Instrument Checks.

**Comment by ben-wetherill** [comment]
#4 looks good now
