### ISSUE TITLE
tab_completeness initial test

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#12]
It looks like tab_completeness is counting the quality control activity types incorrectly.  

For type="summary" and "percent", the denominator should only include regular non-QC activity types ("Field Msr/Obs" or "Sample-Routine").  

For type="summary", the numerator should only include regular non-QC activity types where the Result Measure Qualifier field is not NA.  For example, for DO concentration there should be 19 qualified records.

For type="percent", the numerator should be calculated as follows:

- Field duplicate = number of regular non-QC activity types where the QC reference value is not NA.
- Lab duplicate = number of samples with activity type "Quality Control Sample-Lab Duplicate".
- Field blank = number of samples with activity type "Quality Control Sample-Field Blank".
- Lab blank = number of samples with activity type "Quality Control Sample-Lab Blank".
- Spike/Check = number of samples with activity type "Quality Control Sample-Lab Spike".

It looks like the read_results function is creating some unnecessary rows, such as "Quality Control Sample-Reference Sample".  As mentioned in the vignette review issue, I don't think these should be created.  I also see that they are being counted in the tab_completeness denominator.

**Comment by fawda123** [comment]
@ben-wetherill Can you please check the new output for `tab_completeness()` on the vignette: https://massbays-tech.github.io/MassWateR/articles/qcoverview.html.  I will work on changing the frequency tables this weekend.

**Comment by ben-wetherill** [comment]
The vignette looks accurate, except for this statement...
"the total number of qualified records (those collected for data quality objective checks)".
I'm not sure what that means in the parentheses.  I would describe qualified records as records that have been manually flagged as questionable by the user.

The vignette should probably mention that the datarec field represents only non-QC records.  It excludes duplicates, blanks, and spikes.

Let me know when the function is ready to be tested in R?

**Comment by fawda123** [comment]
@ben-wetherill I've updated the QC frequency and completeness table functions (`tabMWRfre` and `tabMWRcom`).  Can you please check their output in the vignette to make sure I've got the calculations right?

**Comment by ben-wetherill** [comment]
The tabMWRfre function is looking better.  I ran some tests and noticed the following issue:

1. The Number of Data Records (obs) is being calculated incorrectly by qcMWRfre().  For the sample data set, the number of data records for nitrate should be 96, not 88.  The count column seems to be correct.  For TP the number of data records should be 203, not 195.  For pH the number of records is correct 199.
2. The Number of Data Records is correct in tabMWRcom.

The tabMWRcom function looks good.  I don't see any issues.

**Comment by fawda123** [comment]
@ben-wetherill thanks, the number of data records in `qcMWRfre()` (and `tabMWRfre()`) should be correct now.  I was initially removing rows that had entries in `QC Reference Value` column from the count.  I'm still working on splitting the lab spikes/instrument checks.
