### ISSUE TITLE
Column formats in data quality objectives file for accuracy

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#18]
@ben-wetherill just adding this here for the record.  On importing the accuracy file, the `Spike/Check Accuracy` is formatted incorrectly because Excel stores the values as numbers.  There is no way to know which value is a numeric or percentage range for the checks because the values are all imported as numbers, e.g., a number is imported exactly as visually shown, whereas a percentage is converted to a decimal value. Unfortunately, there is no way to have R identify values differently because of how Excel stores the information, i.e., what you see when you open the spreadsheet in Excel is not how the values are stored.  The issue is explained in depth here: https://github.com/tidyverse/readxl/issues/462 One of the many reasons Excel is problematic...

The solution is to convert the column to text in Excel.  I've done this for the example accuracy file, so we should be good to go.  Users will just have to know this is a requirement to correctly use the accuracy check functions.  I've added a better check for the accuracy file to verify that the column formats are correct on import.  See this commit: 100584d348fc43806eacb08093b64763b9c82086

**Comment by fawda123** [comment]
@ben-wetherill I think adding a "<=" sign for entries in the spike/check accuracy clumn would force the cell as text, percent or no, so that would work.  I agree that asking users to save the whole column as text is problematic.

For your second comment, consistency is usually better, so my vote is to enter everything similarly across the columns.  However, the code evaluates the equality operators written exactly as is, if they are provided, i.e., "<" does not include the value, "<=" does.  I'm not sure this is intentional.  It makes sense for the value range column since this describes the entire set of values in question for a parameter.  But, for example, Field Duplicates always include "<=", whereas Field Blanks only include "<".  Was this on purpose or should they all be changed to "<="?  And anything that doesn't have an equality operator is evaluated as "<=" based on absolute difference.

**Comment by fawda123** [comment]
Thanks @ben-wetherill, my vote is for the second file (equality operators in cells, not headers), because it would work with the existing import functions.  I'd have to reprogram the checks and figure out how to transfer the equality opeators to each cell if we were using the first file.  I'd like to continue with the second file if you're okay with that.

**Comment by carrjill** [comment]
I'm fine with keeping the equality operators in the cells vs the headings to avoid undoing work you've already done, @fawda123. With the DQO file only being created once it's not a big ask for groups to format it this way and I find it more flexible as well (e.g. perhaps a group would rather have a field blank DQO for Spec Conductance reported at <=24 as opposed to <25). Not sure how likely that scenario is but added flexibility is rarely a bad thing.

**Comment by ben-wetherill** [comment]
Sounds good to me.
