### ISSUE TITLE
Create time series seasonal function

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#23]
Can be similar to outlier check function in plot format, but no outlier labels and include different plot format types (e.g., boxplot, bars).  Need to include:

* Most options from `anlzMWRoutlier`
* Date filter option
* Site filter option
* Parameter filter required
* Result Attribute option
* Replace BDL, AQL with appropriate values
* Add threhsold lines, specify marine or fresh
* Month or weekly grouping

**Comment by ben-wetherill** [comment]
Looks very good.  Here are my comments:

1. If running for type="bar" or "jitterbar", can we change the title to Average ____?
2. I'm not crazy about the line used for the lower threshold.  I think it should be thinner and more of a line than separate dots.
4. If filtering by site or date, can we add that to the title?

**Comment by fawda123** [comment]
Should all be addressed now, I created a title formatting function that's recycled for the other analysis plot functions.  I figured this was appropriate.  I also redid the line formats for the thresholds, we can discuss further if needed.

**Comment by ben-wetherill** [comment]
Average looks good in the title now.  Date filtering is mentioned, but site filtering does not show up in the title.
Is it possible to put the actual date range in the title?  
The site filter could get long, so maybe we don't want to put that detail in the title.
The threshold line formats look better.

**Comment by fawda123** [comment]
@ben-wetherill I modified the function for the plot titles to include site (only mentions results are filtered by sites and does not include actual site names) and the date range.  The title could get long in some cases, so I also added an optional argument to all of the analysis functions to scale the title size (`ttlsize` argument).

**Comment by ben-wetherill** [comment]
Looks good!
