### ISSUE TITLE
Modifying Plots vignette

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#27]
I don't think we should teach `scale_y_continuous(limits = c(min,max)`, because that actually removes data from the statistics.  It actually changes the boxplots.  For changing the y-axis, we should teach `coord_cartesian(ylim = c(min,max))`.  This changes the axis but does not remove data.

**Comment by ben-wetherill** [comment]
The vignette looks good for the y axis, but I would recommend the other approach for the x axis.  For x you do want to exclude data, so scale_x_continuous is better because it doesn't show the edge of the next boxplot.  However, it may not even make sense to teach the x axis because the user can filter that with the dtrng parameter.  It might be better to only mention the y-axis.

**Comment by fawda123** [comment]
Okay, I agree, I had a thought the x-axis part was redundant with the `dtrng` argument when I edited the vignette.  I will remove it.

**Comment by ben-wetherill** [comment]
Looks good
