### ISSUE TITLE
Corrupt database

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#29]
When trying to type in a function, I received this corrupt database message.  I then restarted R and reinstalled the package and I don't get the message anymore.  So, it's probably not an issue, but just thought I would let you know.
![image](https://user-images.githubusercontent.com/102828718/186931093-dea6c1f8-29a5-45c4-ae8d-dcf03a014376.png)

**Comment by fawda123** [comment]
Yea, I think that happens sometimes when the installation fails.  Since you've been reinstalling multiple versions, something likely got screwed up.  Your solution of reinstalling is the best option for fixing.
