### ISSUE TITLE
qcMWRreview new items

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#31]
A couple new minor things I noticed in the qcMWRreview report:

1. When I enter output_dir = "\~" then the file is placed in my default directory as defined in Tools->Global Options.  But when I enter output_dir = "TestFolder" then the file is placed in a folder named "TestFolder" in my working directory as defined with setwd().  This is minor and it may not be an issue at all.  It may be as-designed for R, but it seemed a little odd.  I expected the "\~" to place it in my working directory.
2. In the output file, the date probably doesn't need to be in table format.  With long dates, like September 8, 2022, the text wraps and looks odd.
3. In the output file, in the Data Completeness table, can you set the default font size in the Censored Records and Notes columns to match the other columns?  The other columns are at size 9, but when I start typing in the Notes column it defaults to 11.  Definitely not critical.
4. When running rawdata = TRUE, the raw data returns in a different order than the summarized data.  In the summary, the order is Field Dups, Lab Dups, Field Blanks, Lab Blanks.  In the raw data it starts with Field Blanks.  Can you make it the same order as the summary?

**Comment by fawda123** [comment]
Thanks @ben-wetherill, responses as follows. 

1. Yes, this is default behavior for R that I can't change.  I doubt many folks will be using `~` for an output directory, but if they are, I'm hoping they know that means their home directory.  On Windows, it should be C:\Users\yourname. I use the tilde path expansion alot to save stuff to my desktop, i.e., ~\Desktop\, which would be C:\Users\mbeck\Desktop.  
2. Done - changed to abbreviated month
3. I don't think this is possible yet, it's a known issue for the flextable package: https://github.com/davidgohel/flextable/issues/153
4. Done

**Comment by ben-wetherill** [comment]
2 and 4 are good now.  3 is not critical.

For 1, what I was trying to do was save to the working directory without creating another folder.  How would I do that?

**Comment by fawda123** [comment]
Ah, sorry that wasn't clear.  You would just use `output_dir = getwd()`.  However, I just made this the default for `qcMWRreview()` and `anlzMWRoutlierall()`, so you don't need to make this explicit anymore.

**Comment by ben-wetherill** [comment]
Perfect
