### ISSUE TITLE
thresholds display in scientific format

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#32]
When I run View(thresholdMWR), the Fresh_1 thresholds display in scientific format and the Marine_1 thresholds display with 5 decimals. Is it possible to make all of the thresholds display numerically? Two decimal places would be fine for everything.

**Comment by fawda123** [comment]
@ben-wetherill all those columns are numeric, so they are displaying numerically, but the presentatation (either significant digits or scientific notation) is defined by the one value in a column that has the greatest number of significant digits.  They all display the same if I round them to two decimal places.  The file has to change to do this, I don't think there's a way to do this strictly with `View()`.

**Comment by ben-wetherill** [comment]
I see they are displaying with 2 or 1 digits now, so that is better.
