### ISSUE TITLE
anlzMWRmap longitude/latitude messages

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#33]
I'm wondering if we should consider trying to remove the messages that display when running maps...
`although coordinates are longitude/latitude, st_intersection assumes that they are planar`
`although coordinates are longitude/latitude, st_intersection assumes that they are planar`
`although coordinates are longitude/latitude, st_intersection assumes that they are planar`
`Warning message:`
`In st_buffer.sfc(., dist = units::set_units(buffdist, degree)) :`
`  st_buffer does not correctly buffer longitude/latitude data`

I found that we can use the suppressMessages() function to hide the first three messages.  This works if I run suppressMessages(analyzeMWRmap()).  Since these messages are only important for large scale maps and maps near the poles, we can probably safely hide them for our solution.

For the warning message, I found this discussion  [https://gis.stackexchange.com/questions/303126/how-to-buffer-a-pair-of-longitude-and-latitude-coordinates-in-r](url).  What do you think?

**Comment by fawda123** [comment]
@ben-wetherill I think I finally got this figured out. Give it a try and let me know if it's fixed.

**Comment by ben-wetherill** [comment]
It looks like it is fixed.  Thank you.
