### ISSUE TITLE
qcMWRreview should handle scenarios with missing QC types

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#37]
This is in regard to issue #5 in the beta list.  We decided to use "na" to identify which QC types were not relevant for a group and that the user could put "na" for a whole QC type for all parameters.  I now receive an error when running the following with the attached DQO files.  It should simply return no QC analysis for these parameters with "na".  It worked fine when I only put "nas" in the freqcomp file, but when I use both I get this error.

`qcMWRreview(fset=fset, "D:/Documents/", output_file = "QCReport", rawdata = TRUE)`
Error in `dplyr::mutate()`:
! Problem while computing `Hit/Miss = dplyr::case_when(...)`.
 The error occurred in row 1.
Caused by error in `parse()`:
! <text>:1:5: unexpected numeric constant
1: 120 NA
        ^
Run `rlang::last_error()` to see where the error occurred.

[ExampleDQOFreqComp_na-types.xlsx](https://github.com/massbays-tech/MassWateR/files/9790183/ExampleDQOFreqComp_na-types.xlsx)
[ExampleDQOAccuracy_na-types.xlsx](https://github.com/massbays-tech/MassWateR/files/9790184/ExampleDQOAccuracy_na-types.xlsx)

**Comment by fawda123** [comment]
@ben-wetherill thanks for example files, it works on my end now.  Give it a check and let me know.

**Comment by ben-wetherill** [comment]
This looks good now.
