### ISSUE TITLE
New QC design for Lab Spikes and Calibration Checks

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#39]
Issue for managing this design change:

The QC Frequency table looks good.

The QC Accuracy summary table looks good, but there are some calculation issues described below.

The QC Accuracy raw data for Lab Spikes / Instrument Checks is missing from the qcMWRreview() report.
`qcMWRreview(fset = fset, output_dir=getwd(), output_file = "QCReport", rawdata = TRUE)`

In the raw data, the Diff/Accuracy is correctly calculated, but the Hit/Miss isn't for parameters where the DQO is defined in percent:
Example 1:  Ammonia 3/21/21 spike=0.08, result=0.02, accuracy=25%, and DQO<=15%.  This should be a miss because 25% is outside 100% +/- 15%.
Example 2:  TP 6/15/21 spike=0.12, result=0.07, accuracy=58% and DQO<=15%.  This should be a miss because 58% is outside 100% +/- 15%.
[BetaResults_10-26-22.xlsx](https://github.com/massbays-tech/MassWateR/files/9871042/BetaResults_10-26-22.xlsx)

**Comment by fawda123** [comment]
@ben-wetherill I think these are fixed now.

**Comment by ben-wetherill** [comment]
This looks good.
