### ISSUE TITLE
Lab Spikes need % recovery

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#42]
I've just identified a new unit of measure need.  Sorry I overlooked this earlier.  When users load Lab Spikes in the Results file, they need the ability to use the unit of measure "% recovery" or "%".  Lab spike data may not always be in units such as mg/L.  It is often just reported as a %.  That's all I receive from my lab.  "% recovery" is the official WQX unit of measure, but I think we should allow "%" also.

I think the QC Accuracy report will handle this fine without any changes, but we need to test it to make sure.

Attached is a new results file with some % examples.
[ExampleResults_11-10-22.xlsx](https://github.com/massbays-tech/MassWateR/files/9983602/ExampleResults_11-10-22.xlsx)

Currently this fails because there are multiple units of measure for the same parameter.

**Comment by fawda123** [comment]
@ben-wetherill that makes sense. I fixed the checks on input by just removing lab spike rows that indicate `%` or `% recovery`.  I also think you're right about the QC accuracy report.  It generated just fine and I think the output makes sense.  

The only minor issue is the filter for the value ranges in the DQO accuracy file.  The rows in the results file with units in percent can't be directly compared to the value ranges in the accuracy file that aren't in percent.  The row that ends up being applied will usually default to the higher value range (e.g., 100 >= 0.05 if recovery rate is 100%, which applies the standard of 15% max diff for TP).  My guess is this creates the right comparison, but just wanted to point it out.  The only time it would be an issue is if the recovery rate is so low, it defaults to the lower value range that reports the standard not in percent.

**Comment by ben-wetherill** [comment]
This looks good now.  The minor issue you mentioned also seems to be fine.  In general, if users are receiving lab spikes in % then they will all be in % and their DQO file would only have one % range, so the scenario probably will never happen.  But, I tested it with a very low recovery of 0.005% and it seemed to work fine.
