### ISSUE TITLE
Miscelaneous WQX output issues

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#46]
Here are a couple items for the WQX output tabMWRwqx():

1. Can you provide a warning if there are sites in the results file that are not listed in the site list?
2. The unit of measure for pH in the WQX output file should be empty, not "blank".  Sorry about the confusion.  There should be nothing in the UOM field for pH.

**Comment by ben-wetherill** [comment]
Sorry.  Correction on number 2.  The pH unit of measure for WQX should be the word "None".

**Comment by fawda123** [comment]
@ben-wetherill these are addressed now.

**Comment by ben-wetherill** [comment]
These both look great!
