### ISSUE TITLE
QC Report Keep with Next setting

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#47]
There is a setting in Word Paragraph - Line and Page Breaks called "Keep with next".  That is turned on for many things in the QC report, which is often good, but it caused issues when I started to move things around.  It forced the tables to be on a single page and created large blank pages at the beginning of the tables.  I had to turn it off to format my report.  I think we should turn it off inside the tables (i.e. inside the frequency and accuracy summary tables and inside the raw data tables).

**Comment by fawda123** [comment]
I'll see what I can do, but I'm not optimistic as this is probably a Word setting that can't be controlled from within R.

**Comment by ben-wetherill** [comment]
It looks to me like the Keep with next setting is unchanged.  It seems to still be defaulting to One everywhere in the QC Report.

**Comment by fawda123** [comment]
Okay, you'll have to show me on our next call so I can more clearly understand the issue. I'm more optimistic this can be fixed, but will need to see the issue on your end.

**Comment by ben-wetherill** [comment]
I see you have already fixed the sequence of tables that we talked about yesterday.  That looks great!

Here are the files for troubleshooting the Keep With Next issue.  It works the same on both of my computers.  The file "QCReport" is how it comes out, with Keep with Next on.  The file "QCReport-KWNfixed" is how we would like it to come out.

[OARS WQXMeta.xlsx](https://github.com/massbays-tech/MassWateR/files/10361464/OARS.WQXMeta.xlsx)
[OARS DQOFreqComp.xlsx](https://github.com/massbays-tech/MassWateR/files/10361465/OARS.DQOFreqComp.xlsx)
[OARS_QCReport.docx](https://github.com/massbays-tech/MassWateR/files/10361466/OARS_QCReport.docx)
[OARS MassWateR load 2022.xlsx](https://github.com/massbays-tech/MassWateR/files/10361467/OARS.MassWateR.load.2022.xlsx)
[OARS_QCReport-KWNfixed.docx](https://github.com/massbays-tech/MassWateR/files/10361468/OARS_QCReport-KWNfixed.docx)
[OARS DQOAccuracy.xlsx](https://github.com/massbays-tech/MassWateR/files/10361469/OARS.DQOAccuracy.xlsx)
[OARS Sites.xlsx](https://github.com/massbays-tech/MassWateR/files/10361470/OARS.Sites.xlsx)

**Comment by ben-wetherill** [comment]
Now the QC Report looks good.  I reinstalled the package directly from Github, and I think Marcus made some updates to the template.
