### ISSUE TITLE
QC checks do not return NULL if missing accuracy value

### ISSUE THREAD

**Issue by fawda123** [massbays-tech/MassWateR#49]
See here: https://massbays.discourse.group/t/error-when-running-qc-review/81

This causes an obscure error because a data frame with zero rows is returned instead of `NULL`, e.g., if QC lab blank samples are included in the results file, but there are no corresponding values in the Spike Check/Accuracy column in the accuracy file.  Easy fix is to add a post-routine at the end of `qcMWRacc()` that reassigns this to `NULL`.

**Comment by ben-wetherill** [comment]
More details about this issue:

If their is no QC data (no QC records and no QC reference values) and there are some qualified records, the following cryptic error is produced.  In the old release, I don't get the error if there are no qualified records (in the new release I do).  There is no point in running the QC review if there is no QC data, but the error message needs to be improved.  Test with "Test_Results_noQC.xlsx".  I get this error in the old release AND the new r-universe release.
> qcMWRreview(fset=fsetls, output_dir = getwd(), 
+             output_file = "QCReport", rawdata = TRUE)
Error in `dplyr::group_by()`:
! Must group by variables found in `.data`.
✖ Column `Parameter` is not found.
[Test_Results_noQA.xlsx](https://github.com/massbays-tech/MassWateR/files/11398605/Test_Results_noQA.xlsx)


I was not able to replicate Becky's issue in the old release.  I tested with the following files - one E.coli Lab Spike and NA in DQO files, but it worked fine.  However, if I use similar files in the new release I get the above error.
[Sample_DQOAccuracy_testNA.xlsx](https://github.com/massbays-tech/MassWateR/files/11398431/Sample_DQOAccuracy_testNA.xlsx)
[Sample_DQOFreqComp_testNA.xlsx](https://github.com/massbays-tech/MassWateR/files/11398432/Sample_DQOFreqComp_testNA.xlsx)
[Test_Results_testNA_old.xlsx](https://github.com/massbays-tech/MassWateR/files/11398433/Test_Results_testNA_old.xlsx)

**Comment by fawda123** [comment]
@ben-wetherill this issue should be fixed now, there's an informative error message that indicates no qc records or reference values if someone attempts to create a QC review file with incomplete data.  The same error will also be triggered if someone tries to create the individual accuracy tables. 

I still think the fix I added for Becky's data in the commit referenced above is appropriate. It solves the issue without adding a bunch of extra code to prevent triggering the subroutine for an invalid QC accuracy check. This seems like a better solution rather than complicating the existing code.  

And I also verified that the QC accuracy checks are using the entries in the frequency and completeness table to screen for missing values, so that wasn't the issue.

**Comment by ben-wetherill** [comment]
Ok.  I think it is working as we want.  The report is created as long as there is one valid QC record or reference value.

I'm thinking that we could improve the error message slightly:
Instead of "No QC records and no QC reference values, cannot create QC tables".  
How about "No QC records or reference values for parameters with defined DQOs.  Cannot create QC tables."?
You do get the error if a parameter has QC records but no corresponding DQOs (or NA DQOs).
