### ISSUE TITLE
Output directory not showing

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#50]
For the following two functions, the confirmation message doesn't say where the file is located.  See attached image.
qcMWRreview()
anlzMWRoutlierall()

tabMWRwqx() is working fine
![output dir 2](https://github.com/massbays-tech/MassWateR/assets/102828718/be727f91-8ae3-455d-b97a-1a5d06a4cf01)
![output dir](https://github.com/massbays-tech/MassWateR/assets/102828718/ffc183f0-1331-4fe3-af5b-e78d0290a3c4)

**Comment by fawda123** [comment]
@ben-wetherill should be fixed now

**Comment by ben-wetherill** [comment]
Looks good
