### ISSUE TITLE
QC Reference Value error

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#52]
In the Results file, if the QC Reference Value column is empty, the tabMWRwqx() function returns an error.  This should be allowed.  If there are no QC duplicates, then this column will be empty.  

We probably need to make this fix soon.

**Comment by fawda123** [comment]
@ben-wetherill this should be fixed now, there's now a quick check that bypassess that section of code in `tabMWRwqx()` if the `QC Reference Value` column has no entries.

**Comment by ben-wetherill** [comment]
This looks good in r-universe.dev.  

Though, it looks like the version is still 2.1.0.

**Comment by fawda123** [comment]
Yea, I've left the version number the same as current CRAN release.  I didn't want to confuse people that visit the main website that use the CRAN download instructions.
