### ISSUE TITLE
Value Range of na in DQO Accuracy

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#54]
This is not critical, but we should probably check the DQO Accuracy file Value Range column for valid values.  "na" is not a valid value for this column.  The valid values are "all", <, <=, >, >=

"na" should return an error.

**Comment by fawda123** [comment]
@ben-wetherill, `readMWRacc()` is setup to automatically convert text entries for "na",  "NA", or empty for any cell in the DQO accuracy file to actual `NA` values in R. So, these "incorrect" entries in the `Value Range` column would be handled correctly and allow the user to continue with downstream analysis.  Would you rather an error be returned prompting a change?  And should this only apply to the `Value Range` column?

**Comment by ben-wetherill** [comment]
This is only for the Value Range column.  NA doesn't make sense in this column because this column is defining what range the other columns are valid for.  NA is not listed as a valid value in the instructions for this column.  I would prefer to error and tell the user to use "all" instead of "na".  But, this isn't critical because everything is working fine now.

**Comment by fawda123** [comment]
No problem, this should throw an error now only if `na` is found in the `Value Range` column.  Any `na` values in other columns are automatically set to `NA` when the accuracy file is imported.  

```r
accpth <- system.file('extdata/ExampleDQOAccuracy.xlsx', package = 'MassWateR')
accdat <- readMWRacc(accpth, runchk = F, warn = F)
accdat$`Value Range`[c(3, 7)] <- 'na'

checkMWRacc(accdat)
```
```
Running checks on data quality objectives for accuracy...

	Checking column names... OK
	Checking all required columns are present... OK
	Checking column types... OK
Error: 	Checking no "na" in Value Range...
	Replace "na" in Value Range with "all" for row(s): 3, 7
```

**Comment by ben-wetherill** [comment]
Looks good.  Thanks.
