### ISSUE TITLE
Warning or Error for incorrect entries

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#61]
Not critical and maybe not an issue, but...

If I type tabMWRacc(fset=fsetls,accchk = "Lab Spike",type = "individual") I just get a warning saying "No data to check for Lab Spike".  Didn't it used to suggest valid accchk entries for me?  It does this for the other parameters.

Conversely...
In tabMWRacc() if you enter type="perc" it understands it as percent.  Shouldn't this return an error?
And it looks like other functions do this too for most parameters.  anlzMWRseason(fset=fsetls,param="DO",group="mon") works.
This definitely isn't a serious issue, but I was wondering if this is the way you wanted it to work.

**Comment by ben-wetherill** [comment]
Ok.  Looks good.  
Though, I am wondering about this message...
`# 'No data to check for Field Blanks, valid accchk entries include Lab Blanks, Field Duplicates, Lab Duplicates, Lab Spikes / Instrument Checks'`
This implies that Field Blanks is not a valid entry.  In the case that would trigger this message, when there are no field blanks in the results table, I think it would be fine for the message to say...
`# 'No data to check for Field Blanks'`

**Comment by fawda123** [comment]
@ben-wetherill no problem, I can just remove that last bit of the message.  However, I was under the impression that we needed to provide an indication of the checks that one could evaluate when data were available.  This is distinct from just evaluating the entry as valid.  The message is misleading as is, which was my mistake.  They are valid entries (an earlier check verifies this) AND the data are available for QC assessments. Would it be better to say something like this? 
`# No data to check for Field Blanks, data available for Lab Blanks, Field Duplicates, Lab Duplicates, Lab Spikes / Instrument Checks`

**Comment by ben-wetherill** [comment]
That is even better.

**Comment by fawda123** [comment]
Okay, it's done. Closing the issue now.  
```r
chk <- resdat %>% 
   filter(!`Activity Type` == 'Quality Control Sample-Field Blank')
tabMWRacc(chk, accdat, frecomdat, runchk = F, warn = T, type = 'individual', accchk = 'Field Blanks')
# No data to check for Field Blanks, data available for Lab Blanks, Field Duplicates, Lab Duplicates, Lab Spikes / Instrument Checks 
```
