### ISSUE TITLE
Some maptypes don't work in anlzMWRmap

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#62]
`anlzMWRmap(fset=fsetls, param="DO", addwater = NULL, maptype = "terrain-background")`
returns
```
Error in f(init, x[[i]]) : 
  number of rows of matrices must match (see arg 2)
```

The following maptypes also do not work:
toner, toner-2010, toner-2011, toner-line, toner-lite, watercolor
The rest of the maptypes do work.

**Comment by fawda123** [comment]
I noticed this as well.  This is not a MassWateR issue - see https://github.com/dkahle/ggmap/issues/353 I'm hopeful a fix will be made available soon.

**Comment by fawda123** [comment]
Sounds like the map services will still be available under a new provider, but with a paid service plan: https://maps.stamen.com/stadia-partnership/ We may need to talk about if we want to keep this for `anlzMWRmap()`.
