### ISSUE TITLE
readMWRacc() doesn't accept more than 2 value ranges

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#63]
After the recent fixes to the DQO Accuracy value range logic, readMWRacc() no longer accepts more than two value ranges for a single parameter.  We originally designed the solution to accept multiple value ranges.  See E.coli in our DQO Accuracy template with 4 value ranges - attached here.  Sorry that I didn't include this in the sample file.

[MassWateR_DQOAccuracy_Template_8-16-23.xlsx](https://github.com/massbays-tech/MassWateR/files/13233156/MassWateR_DQOAccuracy_Template_8-16-23.xlsx)

**Comment by fawda123** [comment]
@ben-wetherill this is fixed now, I just removed the check for more than two rows per parameter in `checkMWRacc()`.  You'll want to verify that the correct value ranges are used for the DQOs when there are multiple ascending value ranges as in the example you provided for E. coli.

**Comment by ben-wetherill** [comment]
This looks like it is working perfectly now.  It doesn't seem to matter what order the value ranges are listed in.  You must have written the logic to be robust regardless of the order.
