### ISSUE TITLE
Data input vignette review

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/MassWateR#9]
I couldn't make adjustments directly in the vignette code because it told me I don't have edit access.

This is great.  Very thorough and easy to read.  It is perfect for me and Jill and maybe a super-user, but I assume you are not thinking that this is what we would use to train the users.  I would make a much simpler training script.

Here is what I noticed:

- [x] 1. In the first paragraph, there is a "WQZ" instead of "WQX".
- [x] 2. When you describe the DQO inputs, I think I would list three things:  accuracy, frequency, and completeness. 
- [x] 3. Why do you say that the site metadata is optional?  I would think it should be considered as required.
- [x] 4. When talking about the example files, you mention that alternative files "can be used".  I'm thinking the more correct term here would be "will be used".  I can't think of any scenarios where users would use the example files we created.
- [x] 5. In the section about reformatting minor issues in the file, you mention creating duplicate rows for entries in the QC reference value field.  This can be complicated, so we should probably talk through it in person.  I would not think of this as a formatting issue.  It is the correct way to format the file.  This row duplication is needed when you create the output file for WQX, but I don't think you need it to do the QA/QC analysis.
- [x] 6. I'm wondering if the function names should have a special code in them to avoid conflict.  The read_results() function could conflict with other packages, don't you think?  Maybe we should put something like "mwr" or "masswater" at the beginning of each function, such as mwr_read_results().

**Comment by fawda123** [comment]
Thanks @ben-wetherill, all good ideas and suggestions here.  I'll make edits in the text as needed and we can discuss any remainder on our bi-weekly call.

**Comment by ben-wetherill** [comment]
Regarding #6, I'm thinking of the USGS dataRetrieval package as an example.  All of its functions include "NWIS" in the name so that you can easily recognize them as dataRetrieval functions:  readNWISuv(), readNWISgwl(), readNWISsite(), readNWISDaily(), renameNWISColumns(), etc.

**Comment by fawda123** [comment]
Alright, I won't push back to hard on that.  Better to rename now rather than later when it gets more complicated.  How about, `readMWRsites()`, `formMWRresults()`, etc.?

**Comment by ben-wetherill** [comment]
Those seem like good names to me.
